In [1]:
import numpy as np

In [2]:
A = np.arange(3,15)

# array([3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
         
print(A[3])    # 6

6


In [3]:
A = np.arange(3,15).reshape((3,4))
"""
array([[ 3,  4,  5,  6]
       [ 7,  8,  9, 10]
       [11, 12, 13, 14]])
"""
         
print(A[2])         

[11 12 13 14]


In [4]:
print(A[1][1])      # 8
print(A[1, 1])      # 8

8
8


In [5]:
print(A[1, 1:3])    # [8 9]

[8 9]


In [6]:
for row in A:
    print(row)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


In [ ]:
for column in A.T:
    print(column)